# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d237935f23020816a58c9b6017273a7e468aeed74dee7263017ec39e9fcb92f9f0333914d3d3173d6941c4a8ed28ae9a936974c428f2437947a3d5788900f70

test:
  secret_key_base: c00187dc531ef4d1a3b725e5a23abd1a5e93f24e902f2e59633cc1e407996232c039331c644c699dbcc99adc9b831535b39ce994f043b3685b49352de0ac46ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
